language: python
python:
  - 3.5
  - 3.6
  - 3.7

services:
  - postgresql
  - virtualenv

before_script:
psql -c 'create database travis_ci_test;' -U postgres
  - psql -c "CREATE DATABASE wellth_water_db;" -U postgres
  - psql -c "CREATE USER wellth_water;" -U postgres
  - psql -c "ALTER USER wellth_water CREATEDB;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES on DATABASE wellth_water_db to welth_water;" -U postgres
  - virtualenv --python=python3 venv
  - source venv/bin/activate
  - pip install -r requirements.txt

script:
  - python manage.py migrate
  - python manage.py test
