language: python
python:
  - 3.6

addons:
  postgresql: "9.6"

before_script:
  - psql -c "CREATE USER wellth_water;" -U postgres
  - psql -c "CREATE DATABASE wellth_water_db WITH OWNER wellth_water;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO public;" -U postgres
  - virtualenv --python=python3 venv
  - source venv/bin/activate
  - pip install -r requirements.txt

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
